name = "GridapMHD"
uuid = "afadc09e-922c-4d62-8330-7a6898d360cc"
authors = ["Jes√∫s Bonilla", "Francesc Verdugo", "Large Scale Scientific Computing"]
version = "0.4.0"

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FlameGraphs = "08572546-2f56-4bcf-ba4e-bab62c3a3f89"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"
GridapDistributed = "f9701e48-63b3-45aa-9a63-9bc6c271f355"
GridapGmsh = "3025c34a-b394-11e9-2a55-3fee550c04c8"
GridapP4est = "c2c8e14b-f5fd-423d-9666-1dd9ad120af9"
GridapPETSc = "bcdc36c2-0c3e-11ea-095a-c9dadae499f1"
GridapSolvers = "6d3209ee-5e3c-4db7-a716-942eb12ed534"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
P4est_wrapper = "3743d7c0-8adf-11ea-380b-7d33b0ecc1da"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
PartitionedArrays = "5a9dfac6-5c52-46f7-8278-5e2210713be9"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SparseMatricesCSR = "a0a7dd2c-ebf4-11e9-1f05-cf50bc540ca1"
gmsh_jll = "630162c2-fc9b-58b3-9910-8442a8a132e6"

[compat]
BSON = "0.3"
FileIO = "1"
Gridap = "0.18"
GridapDistributed = "0.4.0"
GridapGmsh = "0.7.2"
GridapP4est = "0.3.7"
GridapPETSc = "0.5.0"
GridapSolvers = "0.4.0"
MPI = "0.20"
PackageCompiler = "2"
SparseMatricesCSR = "0.6.6"
julia = "1.7"

[extras]
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
